name: ci
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false

      matrix:
        config:
        # FIXME: Windows fails to build EAMain: Error C2664
        #  - { name: "Windows MSVC", os: windows-2019, cc: "cl", cxx: "cl", generator: "Visual Studio 16 2019"}
          - { name: "Ubuntu gcc", os: ubuntu-22.04, cc: "gcc", cxx: "g++", generator: "Unix Makefiles" }
          - { name: "MacOS clang", os: macos-12, cc: "clang", cxx: "clang++", generator: "Unix Makefiles" }

        include:
          - build_type: Release
          - build_tests: ON
          - install_prefix: install
          - build_type: Release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Configure CMake
        run: cmake -S . -B ${{github.workspace}}/build -G "${{matrix.config.generator}}" -DCMAKE_BUILD_TYPE:STRING=${{matrix.build_type}} -DEABASE_BUILD_TESTS:STRING=${{matrix.build_tests}} -DCMAKE_INSTALL_PREFIX:STRING=${{github.workspace}}/${{matrix.install_prefix}} -DCMAKE_CXX_COMPILER:STRING=${{matrix.config.cxx}} -DCMAKE_C_COMPILER:STRING=${{matrix.config.cc}}

      - name: Build

        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: test/EABaseTest

      - name: Install
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target install
